import os
from util import get_names_from_csv
# guards = get_names_from_csv('./guards.csv')

female_guards = ['Alice Orowski', 'Anna Hempel', 'Anneliese Kohlmann', 'Elisabeth Becker', 'Elisabeth Volkenrath', 'Ewa Paradies', 'Frieda Walter', 'Gerda Steinhoff', 'Gertrude Feist', 'Gertrude Saurer', 'Helene Kopper', 'Hermine Braunsteiner', 'Herta Bothe',
                 'Herta Oberheuser', 'Hertha Ehlert', 'Hilde Liesewitz', 'Hildegard Kanbach', 'Hildegard Lohbauer', 'Ilse Forste', 'Ilse Lothe', 'Irene Haschke', 'Irma Grese', 'Jenny-Wanda Barkmann', 'Johanna Bormann', 'Maria Mandl', 'Therese Brandl', 'Wanda Klaff']

nazi_names = ['A Heinrichsbauer', 'Albert Hartl', 'Arthur Nasse', 'Bernd von Brauchitsch', 'Bernhard Dietsche', 'Bernhard Schwarz', 'Bruno Grothe', 'Christoph Graf zu Stolberg-Stolberg', 'EO Mueller', 'EP Jung', 'EW Letsch', 'Edward John Kerling', 'Emil Puhl', 'Erich Sparman', 'Erich Albrecht', 'Erich Darre', 'Erich Hahnenbruch', 'Erich Schroeder', 'Ernest Peter Burger', 'Ernst Buergin', 'Ernst John von Freyend', 'Ernst Korn', 'Ernst Lautz', 'Ernst Schaefer', 'Ernst Tesseraux', 'Erwin Brandt', 'Erwin Lahousen', 'F Schmelter', 'Franz Hupperschwiller', 'Franz Lenner', 'Franz Schlegelberger', 'Franz Xaver Schwarz', 'Frederich Kritzinger', 'Frederick Duquesne', 'Friedhelm Draeger', 'Friedrich Flick', 'Friedrich Jaehne', 'Friedrich Jeckeln', 'Fritz Bartels', 'Fritz Fischer', 'Fritz Gajewski', 'Fritz Grau', 'Fritz Meurer', 'Fritz Popp', 'Fritz Schwalm', 'George John Dasch', 'Gerhard Rose', 'Gregor Ebner', 'Guenther Tesch', 'Gustav Overbeck', 'Gustav von Halem', 'Günther Joel', 'Günther Nebelung', 'H Beringer', 'H Scheurlen', 'H Schmid-Lossberg', 'Hans Bavendamm', 'Hans Dieter Ellenbeck', 'Hans Hahl', 'Hans Jaedicke', 'Hans Johann Beck', 'Hans Kugler', 'Hans Mueller', 'Hans Petersen', 'Hans Werner Aufseß', 'Hans Zimmermann', 'Hans w Rinn', 'Harald Kuehnen', 'Heinrich Buscher', 'Heinrich Ebersberg', 'Heinrich Emmendorfer', 'Heinrich Gattineau', 'Heinrich Heinck', 'Heinrich Lohl', 'Heinrich Sellmer', 'Heinz Kaufmann', 'Helge Auleb', 'Helmut Johannsen', 'Helmuth Felmy', 'Herbert Hans Haupt', 'Herbert Huebner', 'Herbert Klemm', 'Herman Lang',
              'Herman Otto Neubauer', 'Hermann Boehm', 'Hermann Cuhorst', 'Hermann Hartmann', 'Hermann Karoll', 'Hilar Giebel', 'Hor Wagner', 'Inge Viermetz', 'JV Klenck', 'J Goebel', 'Joachim Entzian', 'Johann Gietler', 'Johannes Hermann Mueller', 'Josef Altmeyer', 'Juettner', 'KH Bendt', 'K Lange', 'K Reinhardt', 'K Ruehmer', 'Karl Donitz', 'Karl Hollidt', 'Karl Mummenthey', 'Karl Rasche', 'Karl Schroeder', 'Konrad Kaletsch', 'Konrad Meyer-Hetling', 'Konrad Radunski', 'Kurt Engert', 'Kurt Mayer', 'Kurt Schmidt-Klevenov', 'L Grauert', 'Leo Hepp', 'Leo Petri', 'Lippe Ernst Erbprinz zur', 'Lothar Fendler', 'Max Ilgner', 'Max Sollmann', 'Meerwald dr Willy', 'Metzner Erwin', 'Michel Elmar', 'Ohler Paul', 'OskWelzl', 'Oskar Mueller', 'Oskars Dankers', 'Oswald Pohl', 'Oswald Rothaug', 'Otto Abs', 'Otto Schwarzenberger', 'P Zimmermann', 'Paul Bante', 'Paul Fehse', 'Paul Haefliger', 'Paul Pleiger', 'Paul Riege', 'Paul Scholz', 'Paulmann Werner', 'Philipp Heinrich Hoerlein', 'Reinhard Gehlen 1945', 'Richard Hildebrandt', 'Richard Quirin', 'Rudolf Creutz', 'Rudolf Kerner', 'Rudolf Oeschey', 'Schuebbe', 'Schulz H', 'Stahl Friedrich', 'Uebelhack Friedrich', 'Ulm Otto', 'Ulrich Haberland', 'WP George John Dasch', 'W Laermann', 'W Staudinger', 'W Tippelskirch', 'W Wirth', 'W von Hoven', 'Walter Duerrfeld', 'Walter Greiling', 'Walter Koehler', 'Walter Schellenberg', 'Walter Warlimont Detention Report', 'Werner Thiel', 'Wezel Emil', 'Wilhelm Bonatz', 'Wilhelm Rudolf Mann', 'Wilhelm von Ammon', 'Wilhelm von Ritter', 'Wilhem Keitel', 'Wilmar Hager', 'Wolfgang Mettgenberg']

holocaust_perpetrator_names = ['Adam Ankenbrand', 'Adolf Ott', 'Adolf Pokorny', 'Adolf Theuer', 'Albert Fredrich Schwartz', 'Albert Kesselring', 'Albin Gretsch', 'Alfred Andreas Hofmann', 'Alfried Krupp von Bohlen', 'Alice Orowski', 'Ansgar Pichen', 'Anton Bergmeier', 'Arthur Andrae', 'Arthur Dietzsch', 'August Heinrich Bender', 'Braune Werner', 'Christof Knoll', 'Claus Schilling', 'Cornelius Schwanner', 'Edmund Veesenmayer', 'Eduard Lorenz', 'Eduard Strauch', 'Edwin Katzenellenbogen', 'Emil Buehring', 'Emil Haussmann', 'Emil Mahl', 'Emil Paul Pleissner', 'Erhard Brauny', 'Erich Dinges', 'Erich Muhsfeldt', 'Erich Zoddel', 'Ernst Biberstein', 'Ernst Girzick', 'Ernst Heinrich von Weizsäcker', 'Erwin Schulz', 'Erwin von Helmersen', 'Eugen Steimle', 'F Meurer', 'Felix Ruehl', 'Feodor Fedorenko', 'Franz Hoessler', 'Franz Kraus', 'Franz Six', 'Franz Stofel', 'Franz Trenkle', 'Franz Zinecker', 'Fridolin Puhr', 'Frieda Walter', 'Friedrich Ruppert', 'Friedrich Wetzel', 'Fritz Becher', 'Fritz Buntrock', 'Fritz Fischer', 'Fritz Hintermayer', 'Fritz Klein', 'Fritz ter Meer', 'GFW Pancke', 'GeorgSchallermair', 'Georg König', 'Georg Rickhey', 'Georg Schallermair', 'Georg Schnitzler', 'Georg Weltz', 'Gerhard Rose', 'Gertrude Feist', 'Gertrude Sauer', 'Guido Reimer', 'Gustav Heigel', 'Gustav Nosske', 'Günther Altenburg', 'Hans-Theodor Schmidt', 'Hans Eisele', 'Hans Heinrich Lammers', 'Hans Hoffmann', 'Hans Kurt Eisele', 'Hans Merbach', 'Hans Möser', 'Hans Wolf', 'Hans Wolfgang Romberg', 'Heinrich Buetefisch', 'Heinrich Buuck', 'Heinrich Oster', 'Heinrich Schmidt', 'Heinz Detmers', 'Heinz Jost', 'Heinz Schubert', 'Helene Kopper', 'Helmut Poppendick', 'Helmut Roscher', 'Herbert Kappler', 'Herman Hackman', 'Herman Helbig', 'Hermann Becker Freyseng', 'Hermann Eberle', 'Hermann Grossmann', 'Hermann Krumey', 'Hermann Pister', 'Hermann Schmitz', 'Hilde Liesewitz', 'Hubert Krautwurst',
                               'Ignatz Schlomovicz', 'Joachim Mrugoswsky', 'Joachim Ribbentrop', 'Johana Borman', 'Johann Eichelsdoerfer', 'Johann Kick', 'Johann Kirsch', 'Johann Paul Kremer', 'Josef Fuchsloch', 'Josef Hirtreiter', 'Josef Kestel', 'Josef Kilian', 'Josef Leipold', 'Josef Remmele', 'Juana Bormann', 'Justus Beyer', 'Jürgen Stroop', 'Karl August Genzken', 'Karl Ernst Möckel', 'Karl Frenzel', 'Karl Krauch', 'Karl von Roques', 'Konrad Schaefer', 'Kramer Josef', 'Kurt Blom', 'Kurt Heinrich', 'Leonhard Eichberger', 'Luise Danz 1947', 'Maria Mandel Krakow', 'Martin Gottfried Weiss', 'Martin Karl Hellinger 1945', 'Martin Sandberger', 'Martin Sandberger', 'Mathias Graf', 'Max Johann Marcus Schobert', 'Max Pauly', 'Michael Redwitz', 'Oscar schmitz', 'Oskar Groning.webp', 'Oskar Helbig', 'Oskar Schroeder', 'Otto Ambros', 'Otto Barnewald', 'Otto Bovensiepen', 'Otto Brinkmann', 'Otto Förschner', 'Otto Ohlendorf', 'Otto Ohlendorf', 'Otto Rasch', 'Otto Schulz', 'Otto Wolfgang Gunther Klaus', 'PMO Dzial III SS neg nr-1835', 'P Weingartner', 'Paul-Blobel', 'Paul Blobel', 'Paul Maischein', 'Paul Rostock', 'Peter Betz', 'Peter Merker', 'Philipp Grimm', 'Reiner Stahel', 'Richard Köhler', 'Richard Walenta', 'Rudolf Brandt', 'Rudolf Jacobi', 'Rudolf Suttrop', 'Schubert Heinz', 'Sebastian Schmid', 'Sepp Dietrich', 'Siegfried Handloser', 'Siegfried Ruff', 'Simon Wilhelm', 'Sylvester Filleboeck', 'Ulrich Greifelt', 'Viktor Brach', 'Vinzenz Schoettl', 'Vladislav Ostrovski', 'Waldemar Hoven', 'Waldemar Klingelhöfe', 'Waldemar von Radetzky', 'Walter Blume', 'Walter Buch', 'Walter Haensch', 'Walter Ulbricht', 'Walter Wendt', 'WernerBraune', 'Werner Alfred Berger', 'Werner Greunuss', 'Wilhelm Altenloh', 'Wilhelm Beiglboeck', 'Wilhelm Dorr', 'Wilhelm Friedrich Karl', 'Wilhelm Pfannenstiel', 'Wilhelm Wagner', 'Wilhelm Welter', 'Willi Seibert', 'Willi Tessmann', 'Willi Zwiener', 'Wolfgang Romberg']
belsen_trial_guards = ['Ansgar Pichen', 'Erich Zoddel', 'Franz Stofel', 'Franz Trenkle', 'Ignatz Schlomovicz', 'Kramer Josef', 'Oscar schmitz', 'P Weingartner', 'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9710', 'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9711', 'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9714', 'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9721', 'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9730',
                       'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9731', 'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9736', 'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9740', 'The Liberation of Bergen-belsen Concentration Camp 1945- Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9741', 'The Liberation of Bergen-belsen Concentration Camp 1945 - Portraits of Belsen Guards at Celle Awaiting Trial, August 1945 BU9745 (crop)', 'Vladislav Ostrovski', 'Wilhelm Dorr']
# print(os.listdir())
# female_guards.sort()
# print(female_guards)
# names_only = [os.path.splitext(name)[0] for name in belsen_trial_guards]
# names_only.sort()
# print(names_only)
# names = [name.replace('_', ' ') for name in belsen_trial_guards]
# print(names)
