# This is a basic workflow to help you get started with Actions
name: Scrape images and Publish on S3

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: setup
        id: setup
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"
          run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            python3 -m pytest
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: build python main.py
        id: build
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
        run: |
          python3 main.py
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: data-set
          path: data-set/*
          retention-days: 3

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Upload to S3
        run: aws s3 mb s3://${{ secrets.S3_BUCKET_URI }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "canada-central-1"
